version: "2.1"

volumes:
  shared-database:

services:

  antenna-capture:
    build:
      context: ./antenna-capture
    container_name: antenna-capture
    restart: always
    privileged: true
    network_mode: host
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - shared-database:/database
    environment:
      - TZ=Europe/Paris

  azure-uploader:
    build:
      context: ./smartlease-uploader
    container_name: azure-uploader
    restart: always
    network_mode: host
    depends_on:
      - antenna-capture
    environment:
      - AZURE_IOT_CONNECTION_STRING=HostName=SLHub.azure-devices.net;DeviceId=LakeHotelGeneva;SharedAccessKey=AE0gR0KRPETaAlhwrBHEHNaaYSNXjrgBE48TWIs/gQk=
      - TZ=Europe/Paris

    volumes:
      - shared-database:/database
  db-viewer:
    build: ./db-viewer
    container_name: db-viewer
    restart: always
    network_mode: host
    depends_on:
      - antenna-capture
      - azure-uploader
    ports:
      - "80"
    environment:
      - AZURE_RELAY_ENDPOINT=Endpoint=sb://iothub-ns-slhub-55263259-776c83d324.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=syeO0n3wtmJFLYm+ihoxEOc4QwH9og1/pAIoTEG66Z0=;EntityPath=slhub
      - TZ=Europe/Paris
    volumes:
      - shared-database:/database
    labels:
      io.balena.features.supervisor-api: '1'
  #battery-monitor:
    #build: ./battery-monitor
    #restart: always
    #privileged: true
    #network_mode: host

  watchdog:
    build: ./watchdog
    privileged: true
    network_mode: host
    restart: always
    environment:
      - TZ=Europe/Paris
    labels:
      io.balena.features.supervisor-api: 1
