version: "2.1"

volumes:
  shared-database:

services:

  antenna-capture:
    build:
      context: ./antenna-capture
    container_name: antenna-capture
    restart: always
    privileged: true
    network_mode: host
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - shared-database:/database

  azure-uploader:
    build:
      context: ./smartlease-uploader
    container_name: azure-uploader
    restart: always
    network_mode: host
    depends_on:
      - antenna-capture
    environment:
      - AZURE_IOT_CONNECTION_STRING=HostName=SLHub.azure-devices.net;DeviceId=LakeHotelGeneva;SharedAccessKey=AE0gR0KRPETaAlhwrBHEHNaaYSNXjrgBE48TWIs/gQk=
    volumes:
      - shared-database:/database
  db-viewer:
    build: ./db-viewer
    container_name: db-viewer
    restart: always
    network_mode: host
    depends_on:
      - antenna-capture
      - azure-uploader
    ports:
      - "80"
    volumes:
      - shared-database:/database
    labels:
      io.balena.features.supervisor-api: '1'
  battery-monitor:
    build: ./battery-monitor
    restart: always
    privileged: true
    network_mode: host