version: "2.1"

volumes:
  shared-database:
  logs:

services:

  antenna-capture:
    build:
      context: ./antenna-capture
    container_name: antenna-capture
    restart: always
    privileged: true
    network_mode: host
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - shared-database:/database
    environment:
      - TZ=Europe/Paris

  azure-uploader:
    build:
      context: ./smartlease-uploader
    container_name: azure-uploader
    restart: always
    network_mode: host
    depends_on:
      - antenna-capture
    environment:
      - TZ=Europe/Paris

    volumes:
      - shared-database:/database
      - logs:/logs
  db-viewer:
    build: ./db-viewer
    container_name: db-viewer
    restart: always
    network_mode: host
    depends_on:
      - antenna-capture
      - azure-uploader
    ports:
      - "80"
    environment:
      - TZ=Europe/Paris
    volumes:
      - shared-database:/database
    labels:
      io.balena.features.supervisor-api: '1'
  #battery-monitor:
    #build: ./battery-monitor
    #restart: always
    #privileged: true
    #network_mode: host

  watchdog:
    build: ./watchdog
    privileged: true
    network_mode: host
    restart: always
    labels:
      io.balena.features.supervisor-api: 1
      io.balena.features.i2c: 1
      io.balena.features.dbus: 1
    environment:
      - TZ=Europe/Paris
